package com.skd.majestic;

import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Main entry point for Majestic — a magic and adventure mod (arcane-celestial).
 *
 * <p>Majestic is the <em>content</em> mod of its ecosystem. It builds on three libraries and
 * ships all the concrete content: the Celestial Plane dimension, biomes and structures, bosses
 * (GeckoLib), the spell schools / rituals / research nodes / relics (defined as datapack data
 * via Almanac Core), the questline and the guide book.</p>
 *
 * <ul>
 *   <li><b>astral_core</b> — essence, casting, rituals, research, relics.</li>
 *   <li><b>expedition_core</b> — dimension, structures, boss encounters, loot injection.</li>
 *   <li><b>almanac_core</b> — datapack codecs, JEI, the Vellumli guide bridge.</li>
 * </ul>
 *
 * <p>Full design: {@code docs/DESIGN_MAJESTIC_1-21-1.md}, {@code docs/PROGRESSION.md},
 * {@code docs/CONTENT_MAGIC.md}, {@code docs/CONTENT_WORLD.md}. Content is generated by datagen.</p>
 */
@Mod(Majestic.MOD_ID)
public final class Majestic {

    public static final String MOD_ID = "majestic";

    public static final Logger LOGGER = LoggerFactory.getLogger("Majestic");

    public Majestic(IEventBus modEventBus, ModContainer modContainer) {
        LOGGER.info("Majestic v{} loading", modContainer.getModInfo().getVersion());
        // Content registration (items, blocks, entities, magic, world, datagen, client) is wired
        // here milestone by milestone. See docs/DESIGN_MAJESTIC_1-21-1.md.
    }
}
